#pragma once

#define NRF_LOG_ENABLED 0
#define NRF_LOG_DEFAULT_LEVEL 0

#define NRF_LOG_BACKEND_SERIAL_USES_RTT 1
#define NRF_LOG_BACKEND_SERIAL_USES_UART 0

#define APP_MAILBOX_ENABLED 1

#define UART_CONFIG_LOG_ENABLED 0
#define UART_CONFIG_LOG_LEVEL 0

#define PEER_MANAGER_ENABLED 0

#define GPIOTE_ENABLED 0

#define BUTTON_ENABLED 0

#define CRC16_ENABLED 0

#define FDS_ENABLED 0

#define APP_TIMER_ENABLED 1

#define BLE_DIS_ENABLED 1